Repository OmniLayer/omnicore, pull requests merged in 2018-06, with the labels that each got.

#630 Update checkpoint for block 520000
  src/omnicore/rules.cpp
Labels: consensus, status: ready

#634 Fix fail safe iteration when forming ECDSA point
  src/omnicore/encoding.cpp
Labels: status: ready, wallet

#642 Fix .gitignore conflict tip
  .gitignore
Labels: bug, status: ready

#644 Add activation 3-of-3 activation key
  src/omnicore/activation.cpp
Labels: consensus, status: ready

#649 Fix .gitignore
  .gitignore
Labels: release, status: ready

#650 Add field "issuerbonustokens" to "omni_getcrowdsale"
  src/omnicore/rpc.cpp
Labels: api, status: ready

#651 Update default value for end block of omni_listtransactions
  src/omnicore/rpc.cpp
Labels: api, status: ready
