Repository OmniLayer/omnicore, pull requests merged in 2019-10, with the labels that each got.

#1019 Set fSuccess true on valid wtxNew
  src/omnicore/wallettxbuilder.cpp
Labels: status: ready, wallet

#1022 Fix #1011: different transactions getting the same sortKey in FetchWalletOmniTransactions
  src/index/txindex.cpp
Labels: api, status: ready

#1023 Remove lint white space check
  test/lint/lint-whitespace.sh
Labels: ci and tests, status: ready

#1010 Fix rescan minutes
  src/omnicore/omnicore.cpp
Labels: documentation, status: ready

#1024 Lock cs_main and cs_tally when calling LoadAlerts
  src/omnicore/omnicore.cpp
Labels: performance, status: ready

#1027 Fail funded send TXs with more outputs than expected
  src/omnicore/wallettxbuilder.cpp
Labels: api, status: ready
