Repository OmniLayer/omnicore, pull requests merged in 2019-09, with the labels that each got.

#994 Raise CXX symbol level to 4.5.0
  contrib/devtools/symbol-check.py
Labels: build, status: ready

#997 Bump version to Omni Core 0.6.0
  configure.ac
  src/omnicore/test/version_tests.cpp
  src/omnicore/version.h
Labels: release, status: ready

#998 Add release notes for Omni Core 0.6.0
  src/omnicore/doc/release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.5.0-release-notes.md
Labels: documentation, release, status: ready
