Repository OmniLayer/omnicore, pull requests merged in 2020-10, with the labels that each got.

#1179 Move lock to blockOnchainActive
  src/rpc/misc.cpp
  src/txdb.cpp
Labels: performance, status: ready

#1181 Return error, when using bitcore RPCs without addrindex
  src/rpc/misc.cpp
Labels: api, status: ready

#1177 Add documentation for address index RPCs
  src/omnicore/doc/rpc-api.md
Labels: documentation, status: in progress

#1176 Add release notes for Omni Core 0.9.0
  src/omnicore/doc/release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.8.2-release-notes.md
Labels: documentation, status: ready
