Repository OmniLayer/omnicore, pull requests merged in 2020-11, with the labels that each got.

#1157 [tests] Add test for fee cache
  src/init.cpp
  src/omnicore/dbfees.cpp
  src/omnicore/omnicore.cpp
  test/functional/omni_feecache.py
  test/functional/test_runner.py
  test/lint/check-doc.py
Labels: ci and tests, status: in progress

#1193 Omni overview updates
  src/omnicore/walletutils.h
  src/qt/overviewpage.cpp
Labels: status: ready, user interface

#1200 Update version to 0.9.99 to indicate development
  README.md
  configure.ac
  src/omnicore/README.md
  src/omnicore/test/version_tests.cpp
  src/omnicore/version.h
Labels: release
