Repository OmniLayer/omnicore, pull requests merged in 2020-03, with the labels that each got.

#1082 Update release notes for Omni Core 0.8.0
  src/omnicore/doc/release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.7.1-release-notes.md
Labels: documentation, release, status: ready

#1084 Avoid MakeWallet() when compiled without wallet
  src/omnicore/rpc.cpp
  src/omnicore/rpcrawtx.cpp
Labels: api, status: ready

#1086 Remove redundant function declaration in test
  src/omnicore/test/dex_purchase_tests.cpp
Labels: build, status: ready

#1090 Only evaluate fee cache, when it's activated
  src/omnicore/omnicore.cpp
Labels: consensus, status: ready

#1091 Don't store state every block, when syncing or rescanning
  src/omnicore/omnicore.h
  src/omnicore/persistence.cpp
Labels: performance, persistence, status: ready

#1095 Bump version to Omni Core 0.8.1
  configure.ac
  src/omnicore/test/version_tests.cpp
  src/omnicore/version.h
Labels: release, status: ready
