Repository OmniLayer/omnicore, pull requests merged in 2020-07, with the labels that each got.

#1142 Remove OpenSSL usage from Omni source
  src/omnicore/consensushash.cpp
  src/omnicore/dex.cpp
  src/omnicore/dex.h
  src/omnicore/mdex.cpp
  src/omnicore/mdex.h
  src/omnicore/parsing.cpp
  src/omnicore/persistence.cpp
  src/omnicore/rules.cpp
  src/omnicore/sp.cpp
  src/omnicore/sp.h
Labels: consensus, status: ready

#1098 Change Regtest RPC port to Bitcoin 0.16+ default
  src/chainparamsbase.cpp
Labels: api, status: ready

#1146 Travis OmniJ tests: upgrade to jdk 11 (from JDK 8)
  .travis.yml
Labels: ci and tests, status: ready

#1147 Travis OmniJ tests: upgrade to jdk 11 (from JDK 8)
  ci/test/00_setup_env_native_omnij.sh
Labels: ci and tests, status: ready
