Repository OmniLayer/omnicore, pull requests merged in 2020-09, with the labels that each got.

#1166 Add new transaction type to embed any data
  src/omnicore/createpayload.cpp
  src/omnicore/createpayload.h
  src/omnicore/doc/rpc-api.md
  src/omnicore/omnicore.h
  src/omnicore/rpcpayload.cpp
  src/omnicore/rpctx.cpp
  src/omnicore/rpctxobject.cpp
  src/omnicore/rpctxobject.h
  src/omnicore/rules.cpp
  src/omnicore/rules.h
  src/omnicore/test/create_payload_tests.cpp
  src/omnicore/tx.cpp
  src/omnicore/tx.h
Labels: api, status: ready, wallet

#1168 Support adding a receiver address for "any data" transactions
  src/omnicore/doc/rpc-api.md
  src/omnicore/rpctx.cpp
  src/omnicore/rpctxobject.cpp
  src/omnicore/tx.cpp
Labels: api, status: ready, wallet

#1169 Avoid overflow on reindex with debug enabled
  src/omnicore/omnicore.cpp
  src/omnicore/tx.cpp
Labels: build, status: ready

#1165 Add bitcore indexing
  src/coins.cpp
  src/coins.h
  src/init.cpp
  src/key_io.cpp
  src/key_io.h
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/script/script.cpp
  src/script/script.h
  src/script/standard.cpp
  src/script/standard.h
  src/serialize.h
  src/txdb.cpp
  src/txdb.h
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/validation.h
  test/lint/lint-circular-dependencies.sh
Labels: api, status: ready

#1173 Bump version to 0.9.0
  configure.ac
  src/omnicore/test/version_tests.cpp
  src/omnicore/version.h
Labels: release, status: ready

#1175 Add description for -experimental-btc-balances
  src/omnicore/doc/configuration.md
Labels: documentation, status: ready
