Repository OmniLayer/omnicore, pull requests merged in 2020-05, with the labels that each got.

#1118 Add error text for omni_decodetransaction, when inputs are missing
  src/omnicore/errors.h
  src/omnicore/rpc.cpp
  src/omnicore/rpctxobject.cpp
Labels: api, status: ready

#1116 Bump version to Omni Core 0.8.2
  configure.ac
  src/omnicore/test/version_tests.cpp
  src/omnicore/version.h
Labels: release, status: ready

#1120 Add security policy
  SECURITY.MD
Labels: documentation, status: ready

#1119 Add more information when listing tokens
  src/omnicore/doc/rpc-api.md
  src/omnicore/rpc.cpp
Labels: api, status: ready

#1121 Corrections to display of DEx info
  src/omnicore/dbtxlist.cpp
  src/omnicore/rpctxobject.cpp
Labels: api, status: ready

#1115 Add seperate RPCs for each DEx 1 action
  src/omnicore/doc/rpc-api.md
  src/omnicore/omnicore.cpp
  src/omnicore/rpc.cpp
  src/omnicore/rpctx.cpp
  src/rpc/client.cpp
Labels: api, status: ready

#1125 Pay exact amount for indivisible tokens
  src/omnicore/rpctx.cpp
Labels: api, status: ready

#1117 Add release notes for Omni Core 0.8.2
  src/omnicore/doc/release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.8.1-release-notes.md
  src/omnicore/doc/rpc-api.md
Labels: documentation, status: ready
