Repository OmniLayer/omnicore, pull requests merged in 2021-07, with the labels that each got.

#1231 Gitian Linux confi8g: replace arm 32-bit with arm64 (aarch64)
  contrib/gitian-descriptors/gitian-linux.yml
Labels: build, status: ready

#1228 Add support to add a delegate for managed issuance
  src/omnicore/createpayload.cpp
  src/omnicore/createpayload.h
  src/omnicore/dbspinfo.cpp
  src/omnicore/dbspinfo.h
  src/omnicore/omnicore.h
  src/omnicore/rpc.cpp
  src/omnicore/rpcpayload.cpp
  src/omnicore/rpcrequirements.cpp
  src/omnicore/rpcrequirements.h
  src/omnicore/rpctx.cpp
  src/omnicore/rpctxobject.cpp
  src/omnicore/rpctxobject.h
  src/omnicore/rules.cpp
  src/omnicore/rules.h
  src/omnicore/sp.cpp
  src/omnicore/sp.h
  src/omnicore/test/create_payload_tests.cpp
  src/omnicore/tx.cpp
  src/omnicore/tx.h
  src/rpc/client.cpp
  test/functional/omni_delegation.py
  test/functional/omni_delegation_disabled_rpc.notpy
  test/functional/omni_nonfungibletokens.py
  test/functional/test_runner.py
Labels: api, consensus, status: ready

#1232 Bump release version to 0.11
  configure.ac
  src/omnicore/test/version_tests.cpp
  src/omnicore/version.h
Labels: release, status: ready

#1234 Update RPC docs for delegated issuance
  src/omnicore/doc/rpc-api.md
  src/omnicore/rpctx.cpp
Labels: api, documentation, status: ready

#1233 Update release notes for Omni Core 0.11
  src/omnicore/doc/release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.10.0-release-notes.md
  src/omnicore/doc/rpc-api.md
Labels: documentation, release, status: ready
