Repository OmniLayer/omnicore, pull requests merged in 2021-04, with the labels that each got.

#1213 If watermark not in block index load from state files
  src/omnicore/omnicore.h
  src/omnicore/persistence.cpp
Labels: persistence, status: ready

#1214 Bump version and tests to 0.10
  configure.ac
  src/omnicore/test/version_tests.cpp
  src/omnicore/version.h
Labels: release, status: ready

#1215 Add release notes for Omni Core 0.10
  src/omnicore/doc/release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.9.0-release-notes.md
Labels: documentation, status: ready

#1219 Trim Gitian build targets
  contrib/gitian-descriptors/gitian-linux.yml
  src/omnicore/doc/release-notes.md
Labels: release, status: ready

#1224 Add opcode when calculating Omni class
  src/omnicore/wallettxbuilder.cpp
Labels: status: ready

#1223 Show Omni version in Qt and CLI
  src/bitcoind.cpp
  src/qt/utilitydialog.cpp
Labels: status: ready

#1220 Move test builds to Cirrus
  .cirrus.yml
  .travis.yml
  README.md
  ci/lint/04_install.sh
  ci/lint/05_before_script.sh
  ci/lint/06_script.sh
  ci/lint_run_all.sh
  ci/test/00_setup_env.sh
  ci/test/00_setup_env_mac.sh
  ci/test/00_setup_env_native_nowallet.sh
  ci/test/00_setup_env_native_omnij.sh
  ci/test/00_setup_env_native_qt5.sh
  ci/test/00_setup_env_win64.sh
  ci/test/03_before_install.sh
  ci/test/04_install.sh
  ci/test/05_before_script.sh
  ci/test/06_script_a.sh
  ci/test/06_script_b.sh
  ci/test/wrap-wine.sh
  src/bench/verify_script.cpp
  src/logging.cpp
  src/logging.h
  src/omnicore/dex.cpp
  src/omnicore/doc/release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.4.0-release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.6.0-release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.7.0-release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.7.1-release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.8.1-release-notes.md
  src/omnicore/doc/release-notes/omnicore-0.8.2-release-notes.md
  src/omnicore/log.cpp
  src/omnicore/persistence.cpp
  src/omnicore/wallettxbuilder.cpp
  src/test/descriptor_tests.cpp
  src/test/util/setup_common.cpp
  src/wallet/wallet.cpp
  test/functional/omni_freedexspec.py
  test/functional/omni_freeze.py
  test/functional/rpc_getaddressinfo_label_deprecation.py
  test/functional/test_framework/test_node.py
  test/lint/lint-python.sh
  test/lint/lint-spelling.ignore-words.txt
Labels: ci and tests, status: ready
